### ISSUE TITLE
Need Translators for better experience

### ISSUE THREAD

**Issue by 1998code** [1998code/SwiftNEWKit#8]
### How to contribute to this project?

Steps:
1) Fork this repo https://github.com/1998code/SwiftNEWKit
2) Open Source > SwiftNEW > Localizable.xcstrings
<img width="865" alt="Screenshot 2024-04-22 at 8 22 51 PM" src="https://github.com/1998code/SwiftNEWKit/assets/54872601/d5d0b967-a3a8-4854-b723-9cc96785b465">

3) Add a new language if it has not existed
<img width="865" alt="Screenshot 2024-04-22 at 8 23 26 PM" src="https://github.com/1998code/SwiftNEWKit/assets/54872601/4837893f-07ba-48c6-8207-bba9ce812834">

4) Finally, commit your changes and open a Pull Request for it.

**Comment by AbdelatifAitBara** [comment]
Hi @1998code ,

I was working on the translation into Ar,It,Fr.

I'll make a PR.

**Comment by 1998code** [comment]
Thank you @AbdelatifAitBara

**Comment by 1998code** [comment]
Thank you @NNowakowski for your contribution.

**Comment by 1998code** [comment]
This issue will be closed and moved to the Discussion section.
Thank you.
